-- supabase-init.sql
-- Run this in Supabase SQL editor to create a sample `requests` table.
-- Then create a Storage bucket named `attachments` (public) in the Supabase dashboard.

CREATE TABLE IF NOT EXISTS public.requests (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  outlet_code VARCHAR(16),
  outlet_name TEXT,
  phone VARCHAR(32),
  address TEXT,
  status VARCHAR(32) DEFAULT 'new',
  metadata JSONB,
  created_at TIMESTAMPTZ DEFAULT now()
);

CREATE INDEX IF NOT EXISTS requests_outlet_code_idx ON public.requests (outlet_code);

-- Example insert
-- INSERT INTO public.requests (outlet_code, outlet_name, phone, address) VALUES ('12345678','Outlet A','0123456789','Some address');
